### PR TITLE
[W5.4][T13-A2][Arnol Lim]

### PR DESCRIPTION
**Pull request by arnollim**
Compulsory LO 5.4 for week 5

### CODE REVIEW

**Comment by arnollim** [comment]
Not ready for review yet

**Comment by OscarWang114** [comment]
Congrats on passing the check!
The code is written in OOP style and complies to the SLAP principle. Good!
Just a reminder that commit messages should be imperative, present-tense!

**Comment by XinyiYS** [comment]
A rather interesting command. I see that you follow OOP pretty closely by creating this command in the same way as other command. And you could try and think of other functionalities that enhance the usability of the program and code those in the same fashion you did for this command. Also, try and think of relevant test cases for this command and for other functionalities you think of. Keep up the good work.

Please close this PR after reviewing this comment.

**Comment by arnollim** [comment]
Thank you for your comment Oscar! Yes, I will learn from your proper commit naming convention. It seems more followable to people who might need to follow the project!

**Comment by arnollim** [comment]
Thank you Xinyi for taking the time to review my pull request! 
I did insert I/O Test and JUnit test cases for my new function, but agree that it could be more comprehensive!

I will close the PR

**Pull request closed without merging**
