### PR TITLE
[W5.4][T15-A2]Darren Chin Jhun Pyng

### PR DESCRIPTION
**Pull request by DarrenCzen**
Enhanced addressbook-level2 with sort feature.

### CODE REVIEW

**Comment by 17navasaw** [comment]
Good abstraction used in code for implementation. Updated user guide and expected.txt. Well done!

**Comment by six3oo** [comment]
To sort the address book, why did you create a separate SortCommand class instead of retaining the sort() method within the main AddressBook class?

**Comment by aziziazfar** [comment]
Code was well-written and concise.  The sort command was well implemented

**Comment by K1ang** [comment]
Some comments added. Please close the PR after reading comments.

**Pull request closed without merging**
