### PR TITLE
[W5.4][T13-A2] Henning Tau Frederiksen

### PR DESCRIPTION
**Pull request by coolpotato1**
The list command can now display sublists. Tests have not been updated, due to me starting too late.

### CODE REVIEW

**Comment by XinyiYS** [comment]
Reminder to complete the LO by midnight.Cheers.

**Comment by XinyiYS** [comment]
I see you have made new commits and changes. I will review those. But the Travis Build has not passed, so if you wish to make new commits to make it pass the Travis Build, do so by tonight.

**Comment by XinyiYS** [comment]
It is a rather useful and potentially powerful functionality. Good work including the exceptions. There is a fair amount of OOP being applied and you could go on and practice more on different functionalities.

Do note for the future Compulsory LOs, please do not close PR until I have reviewed it.

**Comment by coolpotato1** [comment]
Hey!
I closed it because I made a new pull request with the updated version close to midnight 3 days ago. Was tired, however, so made a naming mistake. Have you seen the updated version, and is it approved?
Sorry for the inconvenience.

**Pull request closed without merging**
