### PR TITLE
[W5.3b][T16-A2]KENNARD NG POOL HUA

### PR DESCRIPTION
**Pull request by Kennard123661**
Extract commonalities from Phone, Email and Address classes into a parent class called Contact.

### CODE REVIEW

**Comment by Kennard123661** [comment]
Hi Prof @damithc , what does CI build failed mean?

**Comment by Kennard123661** [comment]
Work in progress

**Comment by Kennard123661** [comment]
Ready for review

**Comment by brandonyeoxg** [comment]
Accepting this PR without a review because another of your PRs for this tutorial was reviewed in detail.

**Pull request closed without merging**
