### PR TITLE
[W5.4][W10-A4] Boo Kai Hsien

### PR DESCRIPTION
**Pull request by chrisboo**
This should fail the tests because it is better :)

### CODE REVIEW

**Comment by erik0704** [comment]
Pretty good job, but you still need to update the UserGuide.md

**Comment by Zzmobie** [comment]
Update your user guide!

**Comment by chrisboo** [comment]
Updated. Happy now? 💃

**Comment by nishantbudhdev** [comment]
No issues.
@Zzmobie Maybe you can give a different comment?
@chrisboo Try keeping the comments formal/ civil. 👍

**Pull request closed without merging**
