### PR TITLE
[W5.4][T13-A2] Wang Chih Hao

### PR DESCRIPTION
**Pull request by OscarWang114**
Add edit command for the address book. JUnit tests for edit command are still incomplete.

### CODE REVIEW

**Comment by arnollim** [comment]
Hi Oscar,

Your commits are well named. In constrast, I named my commits according to what I wanted to name them at that point, which might not be ideal for someone else who wants to work on my repository.
I will learn from that.

Your code follows the OOP style very faithfully, such as encapsulation and inheritance. Keep it up.

Your test cases for I/O Testing are very comprehensive. Well Done.

Arnol

**Comment by OscarWang114** [comment]
Thanks for the encouraging comment, @arnollim !

I had a really hard time finding out the correct regular expression in Parser.java for parsing the edit command. 
I will add more JUnit test cases for EditCommand other modified classes, especially the Parser.

**Comment by XinyiYS** [comment]
Looks good, Chin Hao. Neatly compiled commits and well applied OOP. Keep up the good work!
One thing you might want to consider is to try and follow the coding standard format closely, i.e. the indentations and etc. It will make debugging easier later and helps the person reading your code to understand better.

You can close the PR after reviewing this comment.

**Comment by OscarWang114** [comment]
Thank you very much for the comment!  I will close the PR.

**Pull request closed without merging**
